
server:
  port: 8080
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat
    uri-encoding: UTF-8
  servlet:
    context-path: '/'

# 开发期间模板引擎页面修改以后，要实时生效就要：1，禁用模板引擎的缓存。2，ctrl+f9：重新编译。
spring:
  thymeleaf:
    enabled: true
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  resources:
    static-locations: classpath:/static/

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

  aop:
    proxy-target-class: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

#   连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
        min-idle: 8
#       连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        max-idle: 8

#   连接超时时间（毫秒）
    timeout: 0

  # 毫秒，秒，分，时，天
  cache:
    redis:
      timeToLive: 1h


# jta相关参数配置，如果在JTA环境中，仍然希望使用本地事务，可以设置spring.jta.enabled属性为false以禁用JTA自动配置。
  jta:
    enabled: true

# 多数据源配置，注意，如果使用 Druid 的分布式驱动，暂不支持MySql8.0+
  datasource:
    druid:
      # 数据源1
      first:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.xa.DruidXADataSource
        url: jdbc:mysql://localhost:3306/minhow_first?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf8
        username: root
        password: root
        initial-size: 5
        max-active: 20
        min-idle: 1
        # 获取连接时最大等待时间，单位毫秒
        max-wait: 60000
        # 有两个含义：
        # 1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
        # 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
        time-between-eviction-runs-millis: 60000
        # 连接保持空闲而不被驱逐的最小时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        # 使用该SQL语句检查链接是否可用。如果validationQuery=null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
        validationQuery: SELECT 1 FROM DUAL
        # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        test-while-idle: true
        # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-on-borrow: false
        # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-on-return: false
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      # 数据源2
      second:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.xa.DruidXADataSource
        url: jdbc:mysql://localhost:3306/minhow_second?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf8
        username: root
        password: root
        initial-size: 5
        max-active: 20
        min-idle: 1
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validationQuery: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        filters: stat,wall,slf4j
        connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  # jwt配置
  jwt:
    # 加密secret，签名密钥
    secret: sS8yq0!gukLUZ^r$UQgJ2Cd&@3DkT%J96A3XScNwYE*1^SkoV
    # 默认过期时间2小时，单位：秒
    expire-second: 7200
    # JWT加密的密匙
    datakey: hymanSalt


# 指定全局日期解析的格式，默认是按照 / 的方式解析的。所以一般不用单独配置，应该直接在页面中说明。
#  mvc:
#    date-format: yyyy-MM-dd


## mybatis-plus config ###
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  # 实体扫描，多个 package 用逗号或者分号分隔
  typeAliasesPackage: com.hyman.distributed.transaction.pojo.entity
  global-config:
    # 数据库相关配置
    db-config:
      # 主键类型  AUTO:"数据库ID自增"，INPUT:"用户输入ID"，ID_WORKER:"全局唯一ID (数字类型唯一ID)"， UUID:"全局唯一ID UUID";
      id-type: UUID
      # 字段策略 IGNORED:"忽略判断"，NOT_NULL:"非 NULL 判断"，NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      # 驼峰下划线转换
      column-underline: true
      # 数据库大写下划线转换
      #capital-mode: true
      # 逻辑删除配置
      #logic-delete-value: 0
      #logic-not-delete-value: 1
      #db-type: h2
    # 刷新mapper 调试神器
    #refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


#logging:
#  file:
#    path: classpath:/logback-spring.xml

# 所有的配置属性，参考文档：https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/htmlsingle/#common-application-properties。

